django_project/basket/urls.py
from django.urls import path
from basket.views import basket_edit, BasketRemoveView, BasketAddView

app_name = 'basket'

urlpatterns = [
    path('basket-add/<int:product_id>/', BasketAddView.as_view(), name="basket_add"),
    path('basket-remove/<int:pk>/', BasketRemoveView.as_view(), name="basket_remove"),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name="basket_edit")
]

django_project/drf_project/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basket.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/ordersapp/urls.py
from django.urls import path
from .views import OrderList, OrderItemCreate, OrderItemsUpdate, ordering_forming_complete, OrderRead, OrderDelete

app_name = 'ordersapp'

urlpatterns = [
    path('', OrderList.as_view(), name="order_list"),
    path('create/', OrderItemCreate.as_view(), name="orders_create"),
    path('forming/complete/<int:pk>/', ordering_forming_complete, name="ordering_forming_complete"),
    path('read/<int:pk>/', OrderRead.as_view(), name="order_read"),
    path('update/<int:pk>/', OrderItemsUpdate.as_view(), name="order_update"),
    path('delete/<int:pk>/', OrderDelete.as_view(), name="order_delete"),
]

django_project/ordersapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = ((FORMING, 'формируется'),
                            (SENT_TO_PROCEED, 'отправлен в обработку'),
                            (PAID, 'оплачен'),
                            (PROCEEDED, 'обрабатывается'),
                            (READY, 'готов к выдаче'),
                            (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Изменен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING
                              )
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f"Текущий заказ {self.id}"

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

django_project/ordersapp/forms.py
from django import forms
from .models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена за штуку', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

django_project/ordersapp/views.py
from .models import Order, OrderItem
from basket.models import Basket
from .forms import OrderItemForm
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction
from django.forms import inlineformset_factory
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemCreate(CreateView):
    model = Order
    fields = []
    template_name = 'ordersapp/order_create.html'
    success_url = reverse_lazy('ordersapp:order_list')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
            else:
                formset = OrderFormSet()
        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            Basket.objects.filter(user=self.request.user).delete()
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super().form_valid(form)


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    template_name = 'ordersapp/order_create.html'
    success_url = reverse_lazy('ordersapp:order_list')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super().form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:order_list')
    template_name = 'ordersapp/order_delete.html'


class OrderRead(DetailView):
    model = Order
    template_name = 'ordersapp/order_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context

def ordering_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('ordersapp:order_list'))

django_project/ordersapp/templates/ordersapp/inc_order_actions.html
{% if object.status == 'FM' %}
    <button class="btn btn-warning btn-round form-control last" style="width:20%">
        <a href="{% url 'ordersapp:ordering_forming_complete' object.pk %}"> Совершить покупку </a>
    </button>
    <button class="btn btn-default btn-round form-control last">
        <a href="{% url 'ordersapp:order_delete' object.pk %}">Удалить
        </a>
    </button>
{% endif %}
<button class="btn btn-info btn-round form-control last" style="width:20%">
    <a href="{% url 'ordersapp:order_list' %}"> К списку заказов </a>
</button>
<button class="btn  btn-link form-control last">
    <a href="{% url 'index' %}">На главную</a>
</button>

django_project/ordersapp/templates/ordersapp/inc_order_summary.html
<div style="margin-top:100px">
    {% if object %}
    <div class="h3">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}
    </div>
    <hr>
    <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }}
    </div>
    <div class="h4">обновлен: {{ object.updated|date:"Y-m-d H:i:s" }}
    </div>
    <div class="h4">cтатус: {{ object.get_status_display }}
    </div>
    <hr>
    <div class="h4"> общее количество товаров:
        <span class="order_total_quantity">{{ object.get_total_quantity }}</span>
    </div>
    <div class="h4"> общая стоимость:
        <span class="order_total_cost">{{ object.get_total_cost }}</span> руб
    </div> {% else %}
    <div class="h4" style="text-align:center" >Новый заказ
    </div>
    <hr>
    <div class="h4" style="margin-left:30px">Заказчик: {{ user.last_name }} {{ user.first_name }}
    </div> {% if basket.0 %}
    <div class="h4"> общее количество товаров:
        <span class="order_total_quantity">{{ basket.0.get_total_quantity }}</span>
    </div>
    <div class="h4"> общая стоимость:
        <span class="order_total_cost">{{ basket.0.get_total_cost }}</span> руб
    </div> {% endif %} {% endif %}
    <hr>
</div>

django_project/ordersapp/templates/ordersapp/order_create.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
<div style="text-align:center">
    {% include 'ordersapp/inc_order_summary.html' %}
    <div class="order_form">
       <form action="" method="post" >
       {% csrf_token %}
       {{ form.as_p }}
           <table class="table" style="width:60%">
              {{ orderitems.management_form }}
              {% for form in orderitems.forms %}
                  {% if forloop.first %}
                      <thead>
                          <tr>
                              {% for field in form.visible_fields %}
                                  <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                      {{ field.label|capfirst }}
                                  </th>
                              {% endfor %}
                          </tr>
                      </thead>
                  {% endif %}
                  <tr class="formset_row">
                      {% for field in form.visible_fields %}
                          <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                              {% if forloop.first %}
                                  {% for hidden in form.hidden_fields %}
                                      {{ hidden }}
                                  {% endfor %}
                              {% endif %}
                              {{ field.errors.as_ul }}
                              {% if field.name != 'price' %}
                                {{ field }}
                              {% else %}
                                {% if field.value %}
                                    <span class="orderitems-{{forloop.parentloop.counter0}}-price"> {{ field.value }}
                                    </span> руб
                                {% endif %}
                              {% endif %}
                          </td>
                      {% endfor %}
                  </tr>
               {% endfor %}
           </table>
           <div style="width:60%">
               <button type="submit" value="сохранить" style="width:20%" class="btn btn-outline-success">сохранить</button>
               {% include 'ordersapp/inc_order_actions.html' %}
           </div>
       </form>
    </div>

</div>

{%  endblock  %}

django_project/ordersapp/templates/ordersapp/order_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="category_delete" style="text-align:center">
        <div class="h1">Уверены, что хотите удалить?</div>
        {% include 'ordersapp/inc_order_summary.html' %}
        <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
        <a href="{% url 'ordersapp:order_list' %}">отмена</a>
        </button>
    </div>
{% endblock %}

django_project/ordersapp/templates/ordersapp/order_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    <div style="text-align:center">
        {% include 'ordersapp/inc_order_summary.html' %}
        <div class="basket_list">
            {% for item in object.orderitems.select_related %}
            <div class="basket_record">
                <span class="category_name"> {{ item.product.category.name }} </span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price"> {{ item.product.price }}&nbspруб </span>
                <span class="product_quantitiy"> x {{ item.quantity }} шт. </span>
                <span class="product_cost"> = {{ item.get_product_cost }}&nbspруб </span>
            </div> {% endfor %}
        </div>
        {% include 'ordersapp/inc_order_actions.html' %}
    </div>
{% endblock %}

django_project/ordersapp/templates/ordersapp/order_list.html
{% extends 'mainapp/base.html' %}
{% load static %}



{% block content %}
<div class="h3 text-center" style="margin-top:100px">
    Ваши заказы,
    {% if user.first_name %}
        {{ user.first_name|title}}
    {% else %}
        Пользователь
    {% endif %}
</div>
<table class="table orders_list" style="margin-left:50px">
    <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
            {% if item.is_active %}
            <tr>
                <td class="td1 orders_list">{{ item.pk }}</td>
                <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                <td>{{ item.get_status_display }}</td>
                <td>
                    <a href="{% url 'ordersapp:order_read' item.pk %}"> посмотреть </a>
                </td>
                <td> {% if item.status == 'FM' %}
                    <a href="{% url 'ordersapp:order_update' item.pk %}"> редактировать </a>
                    {% endif %}
                </td>
                <td> {% if item.status == 'FM' %}
                    <a href="{% url 'ordersapp:order_delete' item.pk %}"> удалить </a>
                    {% endif %}
                </td>
            </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>
<button class="btn btn-default btn-round" style="margin-left:50px">
    <a href="{% url 'index' %}"> на главную </a>
</button>
<button class="btn btn-default btn-round">
    <a href="{% url 'orders:orders_create' %}"> новый </a>
</button>
{% endblock %}